---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - path: argocd.yaml
  - path: traefik-deleted.yaml
  - path: kubernetes-dashboard-deleted.yaml
  - path: vpa-deleted.yaml
  - path: cnpg-operator-deleted.yaml
  - path: eck-operator-deleted.yaml
  - path: fluentd-deleted.yaml
