---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - path: fluentd.yaml
  - path: traefik-deleted.yaml
  - path: kubernetes-dashboard-deleted.yaml
  - path: minio-operator-deleted.yaml
