---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: sudoku
data:
  MONGO_HOST: "mongodb-svc.mongodb.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_OPTIONS: "replicaSet=mongodb&retryWrites=true&w=majority"
