---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  namespace: elastic
data:
  KIBANA_SCHEME: "http"
  KIBANA_HOST: "kibana-kb-http.elastic.svc.cluster.local"
  KIBANA_PORT: "5601"
