---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
  - tls.yaml
patches:
  - path: traefik.yaml
  - path: envoy-gateway.yaml
  - path: kubernetes-dashboard.yaml
  - path: dragonfly-operator.yaml
  - path: cnpg-operator.yaml
  - path: eck-operator.yaml
  - path: fluentd.yaml
  - path: reloader.yaml
  - path: helm-repositories.yaml
  - path: namespaces.yaml
