---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - path: traefik.yaml
  - path: minio-operator.yaml
  - path: dragonfly-operator.yaml
  - path: cnpg-operator.yaml
  - path: reloader.yaml
  - path: helm-repositories.yaml
  - path: namespaces.yaml
