---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patchesStrategicMerge:
  - traefik.yaml
  - minio-operator.yaml
  - dragonfly-operator.yaml
  - cnpg-operator.yaml
  - helm-repositories.yaml
  - namespaces.yaml
