---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
  - tls.yaml
patchesStrategicMerge:
  - traefik.yaml
  - minio-operator.yaml
  - helm-repositories.yaml
  - namespaces.yaml
