---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - path: traefik-deleted.yaml
  - path: minio-operator-deleted.yaml
  - path: dragonfly-operator-deleted.yaml
  - path: cnpg-operator-deleted.yaml
  - path: eck-operator-deleted.yaml
  - path: cfk-operator-deleted.yaml
  - path: fluentd-deleted.yaml
  - path: reloader-deleted.yaml
