---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../core
  - metallb-ippool.yaml
  - tls.yaml
  - default-storage-class.yaml
  - kubernetes-dashboard-httproute.yaml
patchesStrategicMerge:
  - traefik.yaml
