---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../core
patches:
  - path: metrics-server.yaml
  - path: longhorn.yaml
  - path: keda.yaml
  - path: helm-repositories.yaml
  - path: namespaces.yaml
