---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../core
  - metallb-ippool.yaml
  - tls.yaml
  - kubernetes-dashboard-httproute.yaml
patchesStrategicMerge:
  - traefik.yaml
  - metrics-server.yaml
  - longhorn.yaml
  - keda.yaml
  - helm-repositories.yaml
  - namespaces.yaml
