---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: silence-overcommit
  namespace: prometheus
spec:
  route:
    receiver: "null"
  receivers:
    - name: "null"
  inhibitRules:
    - sourceMatch:
        - name: alertname
          value: KubeCPUOvercommit
          matchType: "="
      targetMatch:
        - name: alertname
          value: KubeCPUOvercommit
          matchType: "="
      equal: ["alertname"]
    - sourceMatch:
        - name: alertname
          value: KubeMemoryOvercommit
          matchType: "="
      targetMatch:
        - name: alertname
          value: KubeMemoryOvercommit
          matchType: "="
      equal: ["alertname"]
