---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - minio-tenant.yaml
  - dragonfly.yaml
  - mongodb.yaml
  - kafka.yaml
  - prometheus-kafka-exporter.yaml
  - prometheus-dashboard-httproute.yaml
  - prometheus-rule-node-cpu-utilization.yaml
  - prometheus-rule-node-memory-utilization.yaml
  - prometheus-rule-pvc-free-space.yaml
