---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - minio-tenant.yaml
  - dragonfly.yaml
  - mongodb.yaml
  - kafka.yaml
  - prometheus-dashboard-httproute.yaml
  - alertmanager-silence-overcommit-config.yaml
