---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-exporter
  namespace: kafka
spec:
  chart:
    spec:
      chart: prometheus-kafka-exporter
      # version: "3.0.0"
      version: "3.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  upgrade:
    remediation:
      retries: 1
  interval: 1m0s
  values:
    replicaCount: 1
    kafkaServer:
      - kafka-kafka-bootstrap.kafka.svc:9092
    kafkaBrokerVersion: "4.1.1"
    kafkaLabels:
      cluster: kafka
      namespace: kafka
    verbosity: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    service:
      type: ClusterIP
      port: 9308
    prometheus:
      serviceMonitor:
        enabled: true
        namespace: prometheus
        interval: 30s
        additionalLabels:
          release: prometheus-stack
        targetLabels:
          - cluster
