---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - path: traefik.yaml
  - path: kubernetes-dashboard.yaml
  - path: minio-operator.yaml
  - path: eck-operator.yaml
  - path: fluentd.yaml
  - path: helm-repositories.yaml
  - path: namespaces.yaml
