---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - metrics-server.yaml
  - metallb.yaml
  - cert-manager.yaml
  - longhorn.yaml
  - service-accounts.yaml
