---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-apps-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:soft-titus/argocd-apps.git
    path: env/javelina/projects/kafka
    directory:
      recurse: true
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sudoku-apps-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:soft-titus/argocd-apps.git
    path: env/javelina/projects/sudoku
    directory:
      recurse: true
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
