---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps
  - argo-app-project.yaml
  - argo-applications-root.yaml
  - kafka-topics.yaml
  - cronjobs.yaml
patches:
  - path: helm-repositories-deleted.yaml
