---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../core
patches:
  - path: longhorn-deleted.yaml
  - path: keda-deleted.yaml
  - path: namespaces-deleted.yaml
