---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../core
patchesStrategicMerge:
  - traefik.yaml
  - metrics-server.yaml
  - keda.yaml
  - kubernetes-dashboard.yaml
  - helm-repositories.yaml
  - namespaces.yaml
