---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps
  - kafka-topics.yaml
  - kafka-delay-requeue.yaml
  - sudoku-puzzle-generator.yaml
  - sudoku-image-generator.yaml
