---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-gateway.yaml
  - traefik.yaml
  - kubernetes-dashboard.yaml
  - vpa.yaml
  - keda.yaml
  - argocd.yaml
  - minio-operator.yaml
  - dragonfly-operator.yaml
  - cnpg-operator.yaml
  - mongodb-operator.yaml
  - eck-operator.yaml
  - kafka-operator.yaml
  - fluentd.yaml
  - prometheus-stack.yaml
  - reloader.yaml
