---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - helm-repositories.yaml
  - envoy-gateway.yaml
  - traefik.yaml
  - kubernetes-dashboard.yaml
  - minio-operator.yaml
  - dragonfly-operator.yaml
  - cnpg-operator.yaml
