---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmaps.yaml
  - secrets.yaml
  - core.yaml
  - core-extension.yaml
  - infrastructure.yaml
  - infrastructure-extension.yaml
  - apps.yaml
