---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configmaps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./configmaps/env/felabella
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
